"""
Computes a CAUSAL (streaming/windowed) repetition count for every packet in
the raw dataset -- fixing the transductive flaw identified by Nevin's Claude:
the original repetition_count/repetition_fraction was computed over each
evaluation split's ENTIRE population, including rows that occur "after" any
given packet. A real, deployed streaming detector could never do that -- it
scores each packet using only what it has already seen.

Fix: process the raw file in its ORIGINAL row order (a reasonable proxy for
packet-capture chronology -- Payload-Byte/CICFlowMeter output preserves
per-day capture order, and this is stated as an assumption, not verified
against ground-truth timestamps) with a sliding window of the last W
packets. For each packet, count only how many of the PRECEDING W packets
share its exact template (payload bytes + ttl + total_len + protocol) --
never looking forward. This is what a streaming detector could actually
compute online, in real time, as packets arrive.

Note on window units: WINDOW_SIZE is expressed in packet COUNT, not wall-
clock time. t_delta's exact semantics (time since previous packet in the
same flow, vs. a global capture-time delta) could not be verified from the
Payload-Byte documentation, so a time-based window was avoided rather than
built on an unverified assumption.

Output: a compact CSV mapping orig_index -> causal_repetition_count, meant
to be rejoined onto train/val/test_known/test_zero_day (which must have
been generated by the updated preprocess_cicids.py that preserves
orig_index) via build_symbolic_kg_causal.py.

Run:
    py compute_causal_repetition.py
"""

import numpy as np
import pandas as pd
from pathlib import Path
from collections import deque, Counter

RAW_PATH = Path(r"E:\NeuroSymbolic-IDS1\data\CICIDS_converted_data.csv")  # shared, read-only
OUT_PATH = Path(r"E:\NeuroSymbolic-IDS1\causal_kg\data\causal_repetition.csv")  # NEW location
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

WINDOW_SIZE = 5000  # preceding packets considered "recent history" --
                     # a design parameter, not fit from data (see docstring)

print(f"Loading {RAW_PATH} (original row order preserved -- this is the "
      f"chronology assumption the causal window relies on)...")

byte_cols = [f"payload_byte_{i}" for i in range(1, 1501)]
usecols = byte_cols + ["ttl", "total_len", "protocol"]
dtype_map = {c: "uint8" for c in byte_cols}
dtype_map.update({"ttl": "uint8", "total_len": "uint16", "protocol": "category"})

df = pd.read_csv(RAW_PATH, usecols=usecols, dtype=dtype_map)
print(f"Raw shape: {df.shape}")

n = len(df)
byte_vals = df[byte_cols].values
ttl_vals = df["ttl"].values.astype(np.int64)
total_len_vals = df["total_len"].values.astype(np.int64)
protocol_codes = df["protocol"].cat.codes.values.astype(np.int64)

print(f"\nRunning causal sliding-window pass over {n} rows "
      f"(window = {WINDOW_SIZE} preceding packets)...")
print("This is a single O(N) pass; expect several minutes given the "
      "per-row hashing and dict bookkeeping.")

window = deque(maxlen=WINDOW_SIZE)
window_counts = Counter()
causal_repetition = np.empty(n, dtype=np.int32)

for i in range(n):
    # Template key: exact payload bytes + ttl + total_len + protocol,
    # matching the same definition used throughout this project.
    key = (byte_vals[i].tobytes(), ttl_vals[i], total_len_vals[i], protocol_codes[i])
    k_hash = hash(key)

    # Count of this template already in the PRECEDING window -- BEFORE
    # adding the current row. This is the causal score: "how many times
    # have I seen this exact packet in the recent past", nothing more.
    causal_repetition[i] = window_counts[k_hash]

    # Add current row to the window, evicting the oldest if over capacity.
    if len(window) == WINDOW_SIZE:
        oldest = window.popleft()
        window_counts[oldest] -= 1
        if window_counts[oldest] == 0:
            del window_counts[oldest]
    window.append(k_hash)
    window_counts[k_hash] += 1

    if (i + 1) % 200_000 == 0:
        print(f"  processed {i+1}/{n} rows...")

out_df = pd.DataFrame({
    "orig_index": np.arange(n),
    "causal_repetition_count": causal_repetition,
})
out_df.to_csv(OUT_PATH, index=False)

print(f"\nSaved causal repetition counts -> {OUT_PATH}")
print(f"Window size used: {WINDOW_SIZE} packets")
print(f"causal_repetition_count stats: min={causal_repetition.min()}, "
      f"max={causal_repetition.max()}, mean={causal_repetition.mean():.2f}, "
      f"P99={np.percentile(causal_repetition, 99):.1f}")
print("\nNext: run build_symbolic_kg_causal.py to rejoin this onto your "
      "train/val/test splits and re-derive the flood rule causally.")
